name: Deploy bot app to GitHub Pages

on:
  push:
    branches:
      - develop
permissions: read-all
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      LANGBASE_API_KEY: ${{ secrets.LANGBASE_API_KEY }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Build
      run: |
        npm install
        npx tsx index.ts
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: src
