name: Deploy bot app to GitHub Pages

on:
  push:
    branches:
      - develop
permissions: read-all
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      env:
        LANGBASE_API_KEY: ${{ vars.LANGBASE_API_KEY }}
        BOT_TOKEN: ${{ vars.BOT_TOKEN }}

    - name: Build
      run: |
        npm install
        npx tsx index.ts
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: src
